// front/src/lib/authentication/SignIn.svelte
<script>
	import "./auth.scss";
	import InputErrors from "../InputErrors.js";
	import SignInUser from "../models/SignInUser.js";
	import AuthService from "../services/AuthService.js";
	import { goto } from '$app/navigation';

	let signInUser = new SignInUser();
	let errors = {
		username: "",
		password: ""
	};

	function handleKeydown(event) {
		if (event.key === "Enter")
			submitSignIn();
	}

	function submitSignIn() {
		console.log("submitSignIn ->", signInUser);
		errors.username = InputErrors.username(signInUser.username);
		errors.password = InputErrors.password(signInUser.password);

		// Check if there is an error, if so, return
		for (let prop in errors)
			if (errors[prop] !== "") return ;

		// If no errors then submit it for real
		AuthService.postSignIn(signInUser);
	}
</script>

<svelte:window on:keydown={handleKeydown}/>

<div class="card">
	<div class="form vflex flex-align-center gap">
		<div class="vflex gap text-left flex-align-center">
			<h1>Sign In</h1>
			<div class="vflex minigap">
				<span>Username</span>
				<input type="text" spellcheck="false" bind:value={signInUser.username}>
				<div class="error">{ errors.username }</div>
			</div>
			<div class="vflex minigap">
				<span>Password</span>
				<input type="password" spellcheck="false" bind:value={signInUser.password}>
				<div class="error">{ errors.password }</div>
			</div>
		</div>
		<div class="hflex gap flex-align-center">
			<button class="button btn-signin" on:click={() => submitSignIn()}>Sign in!</button>
		</div>
		<div class="anchor forgot-password" on:click={() => goto('/forgot-password')}>You forgot your password ?</div>
	</div>
</div>

// front/src/app/sign-in/sign-in.component.ts
import { Component, OnInit } from '@angular/core';
import { Output, EventEmitter } from '@angular/core';

import { LoginUser } from '../models/LoginUser';
import { InputErrors } from '../utils/InputErrors';

@Component({
    selector: 'app-sign-in',
    templateUrl: './sign-in.component.html',
    styleUrls: ['./sign-in.component.scss']
})
export class SignInComponent implements OnInit {

    // We decorate the variable to let know the parent that this will be a catchable event
  @Output()
  isSignin = new EventEmitter<boolean>();
  loginUser: LoginUser = new LoginUser();
  inputErrors = new InputErrors();
  errors: any = {};

  constructor() { }

  ngOnInit(): void { }

  enterSubmit(event: KeyboardEvent) {
    if (event.key === "Enter")
      this.submitSignin();
  }

  submitSignin() {
    console.log("submitLogin ->", this.loginUser);
    this.errors.username = this.inputErrors.username(this.loginUser.username);
    this.errors.password = this.inputErrors.password(this.loginUser.password);

    // Check if there is an error, if so, return
    for (let prop in this.errors) {
      if (this.errors[prop] !== "")
        return ;
    }

    // If no errors then submit it for real
    console.log("-- wow no errors for sign in ! --");
  }

  closeForm() {
    this.isSignin.emit(false);
  }
}

<div class="card vflex gap flex-align-center">
	<div class="form-title">Sign In</div>
	<form class="vflex gap" (keydown)="enterSubmit($event)">
		<div class="vflex minigap">
			<label for="username">Username (this will be used to login)</label>
			<input type="text" name="username" id="username" [(ngModel)]="loginUser.username">
			<div class="error">{{ errors?.username }}</div>
		</div>
		<div class="vflex minigap">
			<label for="password">Password (this will be used to login)</label>
			<input type="password" name="password" id="password" [(ngModel)]="loginUser.password">
			<div class="error">{{ errors?.password }}</div>
		</div>
	</form>
	<div class="hflex gap flex-align-center">
		<button class="button cross" (click)="closeForm()">X</button>
		<button class="button" (click)="submitSignin()">Sign in!</button>
	</div>
</div>
